feat(ci): migrate sonar analysis and nightly from Drone to GitHub Actions
Signed-off-by: Ashim Shrestha <ashimshrestha2384@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,8 +4,12 @@ on:
   push:
     branches:
       - main
+    tags:
+      - 'v*'
   pull_request:
   workflow_dispatch:
+  schedule:
+    - cron: "0 0 * * *" # Every day at midnight
 
 env:
   COMPOSER_HOME: ${{ github.workspace }}/.cache/composer
@@ -13,7 +17,7 @@ env:
 
 jobs:
   php-checks:
-    name: PHP checks
+    name: php checks
     runs-on: ubuntu-latest
 
     steps:
@@ -41,7 +45,7 @@ jobs:
         run: make test-php-phan
 
   php-unit-tests:
-    name: php unit tests ${{ matrix.php-version }} with coverage
+    name: php unit tests (${{ matrix.php-version }}-with-coverage)
     runs-on: ubuntu-latest
     needs: php-checks
     strategy:
@@ -69,12 +73,12 @@ jobs:
         run: make test-php-unit
 
       - name: coverage rename
-        run: mv tests/output/clover.xml tests/output/clover-unitTests-${{ matrix.php-version }}.xml
+        run: mv tests/output/clover.xml tests/output/clover-php-unit-${{ matrix.php-version }}.xml
 
       - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
         with:
           name: coverage-unitTests-${{ matrix.php-version }}
-          path: tests/output/clover-unitTests-${{ matrix.php-version }}.xml
+          path: tests/output/clover-php-unit-${{ matrix.php-version }}.xml
           retention-days: 1
 
   build-ocis:
@@ -92,10 +96,29 @@ jobs:
       - name: get ocis commit ID
         run: |
           source .ci.env
-
-          if [ "${{ matrix.branch }}" = "master" ]; then
+          if [ "${{ github.event_name }}" = "schedule" ]; then
+            echo "Nightly run, fetching latest commit based on branch"
+          
+            if [ "${{ matrix.branch }}" = "master" ]; then
+            REF=master
+            else
+            REF=stable-8.0
+            fi
+          
+            LATEST_OCIS_COMMIT=$(curl -s "https://api.github.com/repos/owncloud/ocis/commits?sha=$REF" | jq -r '.[0].sha')
+          
+            if [ -z "$LATEST_OCIS_COMMIT" ]; then
+            echo "Failed to fetch latest commit for $REF"
+            exit 1
+            fi
+          
+            echo "OCIS_COMMIT=$LATEST_OCIS_COMMIT" >> "$GITHUB_ENV"
+            echo "OCIS_REF=$REF" >> "$GITHUB_ENV"
+          
+          elif [ "${{ matrix.branch }}" = "master" ]; then
             echo "OCIS_COMMIT=$OCIS_COMMITID" >> "$GITHUB_ENV"
             echo "OCIS_REF=$OCIS_BRANCH" >> "$GITHUB_ENV"
+          
           else
             echo "OCIS_COMMIT=$OCIS_STABLE_COMMITID" >> "$GITHUB_ENV"
             echo "OCIS_REF=$OCIS_STABLE_BRANCH" >> "$GITHUB_ENV"
@@ -158,7 +181,7 @@ jobs:
           retention-days: 1
 
   php-integration-tests:
-    name: php integration tests (${{ matrix.php-version}}-${{ matrix.branch }}-${{ matrix.branch == 'master' && matrix.php-version == '8.1' && '-with coverage' || '' }})
+    name: php integration tests (${{ matrix.php-version}}-${{ matrix.branch }}${{ matrix.branch == 'master' && matrix.php-version == '8.1' && '-with-coverage' || '' }})
     runs-on: ubuntu-latest
     needs: build-ocis
     strategy:
@@ -251,13 +274,13 @@ jobs:
 
       - name: coverage rename
         if: matrix.branch == 'master' && matrix.php-version == env.DEFAULT_PHP_VERSION
-        run: mv tests/output/clover.xml tests/output/clover-integrationTests-${{ matrix.php-version }}.xml
+        run: mv tests/output/clover.xml tests/output/clover-php-integration-${{ matrix.php-version }}.xml
 
       - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
         if: matrix.branch == 'master' && matrix.php-version == env.DEFAULT_PHP_VERSION
         with:
           name: coverage-integrationTests-${{ matrix.php-version }}
-          path: tests/output/clover-integrationTests-${{ matrix.php-version }}.xml
+          path: tests/output/clover-php-integration-${{ matrix.php-version }}.xml
           retention-days: 1
 
   docs:
@@ -292,3 +315,27 @@ jobs:
           publish_dir: docs-hugo
           publish_branch: docs-hugo
           force_orphan: true
+
+  sonar-analysis:
+    name: sonar analysis
+    runs-on: ubuntu-latest
+    needs: [php-unit-tests, php-integration-tests]
+    steps:
+      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+        with:
+          fetch-depth: '0'
+
+      - name: download tests coverage
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        with:
+          pattern: coverage-*
+          path: results/
+          merge-multiple: 'true'
+
+      - name: list-coverage-results
+        run: ls -l results
+
+      - name: sonarcloud
+        uses: SonarSource/sonarqube-scan-action@299e4b793aaa83bf2aba7c9c14bedbb485688ec4 # v7.1.0
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
